Added loss condtion: when an enemy hits a player
xxfast/SwipeWarriors pull request #14
Opened 2017-04-11 13:34 UTC by Xavier-Gibbon

As the title says

2017-04-11 13:34 UTC, Xavier-Gibbon commented
![](https://github.trello.services/images/mini-trello-icon.png) [Feature - Loss Condition: Player Losses when hit by enemy.](https://trello.com/c/EIznI1Hp/6-feature-loss-condition-player-losses-when-hit-by-enemy)

2017-04-11 13:54 UTC, JPGalovic requested changes
Game should Halt upon been hit. this is a loss condition.

2017-04-11 13:54 UTC, 6819710 commented on Assets/Scripts/PlayerAndEnemyContact.cs
> +            LossText.text = "YOU LOSE!";
Text is difficult to read

Game Continues after "Game Over"

2017-04-12 02:23 UTC, JPGalovic approved these changes

2017-04-12 02:44 UTC, merged