Horde spawning director
xxfast/SwipeWarriors pull request #20
Opened 2017-04-14 10:59 UTC by xxfast

2017-04-14 11:10 UTC, xxfast commented
![](https://github.trello.services/images/mini-trello-icon.png) [Director Mechanic - Horde Spawning](https://trello.com/c/wvaN1Fn5/7-director-mechanic-horde-spawning)

2017-04-18 10:18 UTC, JPGalovic submitted a review, later dismissed
System works well and setup is simple enough

Need some details about what each element does.

Spawn Distance, Spawn Freq, Spawn for.

Ideally if possible it would be good to enter details for a wave as both a set of enemy types but a number of each, ie I want to spawn 3 basic and 1 aggressive enemy for the wave.

also is it best to have a time limit between each wave or simply next wave on completion of current wave? not a change but worth a thought.

2017-04-18 10:18 UTC, 6819710 commented on Assets/Scripts/EnemySpawner.cs
> +	public void attachProfile(WaveProfile toAttach){
Need detail about what each of these do

2017-04-20 00:42 UTC, xxfast commented on Assets/Scripts/EnemySpawner.cs
> +	public void attachProfile(WaveProfile toAttach){
done

2017-04-20 00:46 UTC, xxfast commented on Assets/Scripts/EnemySpawner.cs
> +	public void attachProfile(WaveProfile toAttach){
as of right now, the enemy spawner will spawn enemies assigned in random order.

2017-04-20 00:47 UTC, xxfast commented on Assets/Scripts/EnemySpawner.cs
> +	public void attachProfile(WaveProfile toAttach){
And about the time between the waves, definitely an interesting approach, but its out of the scope of this task according to the description

2017-04-23 01:35 UTC, xxfast commented
I like the ideas you've suggested,  but its out of the scope of this task according to the description. Well work on them as a separate card

2017-04-23 07:16 UTC, 6819710 commented
you still need to indicate what Spawn Distance, Spawn Freq, Spawn For actully do.

In general comment your code as it is not obvious what the above mentioned feilds actully do.

2017-04-23 07:18 UTC, JPGalovic requested changes
Comment Spawn Distance, Spawn Freq, Spawn for

needs to be clear what these do.

not beyond scope of task

2017-04-23 07:37 UTC, 6819710 commented on Assets/Scripts/WaveProfile.cs
> +﻿using System.Collections;
Cool, so by my understanding the enemy spawns at a frequency of x or y seconds, so to work out number of enemies you take spawnFor and devide by spawnFrequancy

2017-04-23 07:39 UTC, JPGalovic approved these changes
Looks Good.

It is now clear how spawning frequancy works.

Some minor cleanup tasks to complete.

2017-04-23 07:39 UTC, 6819710 commented on Assets/Scripts/WaveProfile.cs
> +	public float spanwFrequency;
Will need to correct spelling of variable name here but thats for cleanup.

2017-04-23 07:40 UTC, merged