Add: Player health
xxfast/SwipeWarriors pull request #48
Opened 2017-05-08 02:49 UTC by xxfast

player now has its own health, and its reflected by the size of the player. Changed enemies attack behaviour so that it deals damage to health of the player

2017-05-08 02:58 UTC, xxfast commented
![](https://github.trello.services/images/mini-trello-icon.png) [Player Mechanic - Health](https://trello.com/c/CVBmeQru/26-player-mechanic-health)

2017-05-08 05:18 UTC, JPGalovic requested changes
In adition to changes to be made, wont the scaling the player to indicate the players health clash with the size changing pickups? namely, if a player shrinks or grows based on hp wont the scales have issue when reseting or changing scale, a better implementation will be simply a hp bar display, which in it self is a seperate task.

2017-05-08 05:18 UTC, 6819710 commented on Assets/Scripts/Health.cs
> +			Destroy (this.gameObject);
This breaks enemies, the pickup spawner is responsible for the deletion of the enemies not the health. the health simply keeps track of what the health is.

Funcionality for player should be included in the loss event handling.

2017-05-08 05:18 UTC, 6819710 commented on Assets/Scripts/Health.cs
> +	public int currentHealth;
keep this private, if you need to display the health in the inspector use the [SerializeField] command to make it visible.

this does not need to be public , especially when you have a getter below

2017-05-08 05:21 UTC, 6819710 commented
I also noticed that there are inconsistant bugs from scene to scene, in the test scene the player cannot collide with the pickups, where in the sword scene the player cannot collide with the enemies.

2017-05-09 07:38 UTC, xxfast commented on Assets/Scripts/Health.cs
> +			Destroy (this.gameObject);
Actually, the change you did broke the enemies. For instance I noticed that enemies who are not spawning anything, are not destroyed in the the scene. Thats clearly a bug. Enemies need to be destroyed by the health script.

2017-05-09 07:38 UTC, xxfast commented on Assets/Scripts/Health.cs
> +	public int currentHealth;
yup, this is a mistake

2017-05-09 14:04 UTC, JPGalovic approved these changes

2017-05-09 14:04 UTC, 6819710 commented on Assets/Scripts/Health.cs
> +			Destroy (this.gameObject);
Ill allow this for this version because time nessasatates it, I will be putting down that full component design should be used in future.

2017-05-09 14:04 UTC, 6819710 commented on Assets/Scripts/Health.cs
> +	public int currentHealth;
Minute enough to let through

2017-05-09 14:04 UTC, merged